theme: jekyll-theme-hacker
title: Daniel Maia
description: Pela experiência e observação, há uma busca constante pela inovação e automação com a liberdade do código.
url: https://diasdmhub.github.io
repository: diasdmhub/portifolio-mark
